### ISSUE TITLE
2023/3/1 | index.htmlで見たい国を選択してすると、googleMap.jsの座標がその国の場所に変わるようにするためのデータを作成

### ISSUE THREAD

**Issue by Code1964** [Code1964/Globe-learning#28]
注意：下記のリストを尊重して下さい
## Checklist when creating the issue

- [x] "Labels"を追加
- [x] "Assignees"を追加
- [x] タスクの詳細を追加
- [x] タスクのチェックリストを作成
- [x] 推定時間を追加

## Task Description (タスク詳細)
- [ ] index.htmlのformの中身がflaskに合っていないので、機能するように変更する
- [ ] 送信ボタンを押すと、javascriptにある座標が選んだ国になる
- [ ] jsonファイルの作成
googleMap.jsに記載されている
`center: new google.maps.LatLng(35.681236,139.767125)`
このコードの数値を変えてほしいです

#### 必ずすべての箇所を記入してください！じゃないと困ります！

    - どんな問題があるか、UIの場合はスクショもつけてください:

    - その問題はどこで発生していますか？:

    Solution (解決策):

    Time estimated to complete (完了推定時間):

## Checklist to complete before closing the issue (イシューを閉じる前のチェックリスト)

- [ ] ローカル環境でアプリの状態を確認してください。あなたの解決策は正しく機能していますか？
- [ ] Overviewを記入する

## Overview

**Investigation time (調査時間）：**
**Implementation time (実装時間）：**

**Comment by naka-c1024** [comment]
jsonファイルではないが，国とそれに対応する緯度経度のデータ取得完了
